/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;
import java.util.*;
import modelo.*;
import javax.swing.*;

/**
 *
 * @author miche
 */
public class FrmMenu extends javax.swing.JFrame {

    public static ArrayList<String> ListaId= new ArrayList();
    Validaciones v=new Validaciones();
    public FrmMenu() {
        initComponents();  
        setLocationRelativeTo(null);
        jPanelJunto.setVisible(false);
        this.btnCompras.setEnabled(false);
        
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel20 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanelFondo = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        btnPersonaNatural = new javax.swing.JButton();
        btnPersonaJuridica = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        BtnPedidos = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jPanelJunto = new javax.swing.JPanel();
        jPanelAmbos = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        txtDireccionN = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        txtTelefonoN = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        txtCorreoN = new javax.swing.JTextField();
        lblDire = new javax.swing.JLabel();
        lblTel = new javax.swing.JLabel();
        lblCorreo = new javax.swing.JLabel();
        jPanelNatural = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        txtNombre1 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtNombre2 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtApellido1 = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtApellido2 = new javax.swing.JTextField();
        txtDocumento = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        lblNom1 = new javax.swing.JLabel();
        lblNom2 = new javax.swing.JLabel();
        lblApell1 = new javax.swing.JLabel();
        lblApell2 = new javax.swing.JLabel();
        lblDocum = new javax.swing.JLabel();
        jPanelJuridica = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        txtRazonSocial = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        txtNit = new javax.swing.JTextField();
        lblRazon = new javax.swing.JLabel();
        lblNit = new javax.swing.JLabel();
        btnCompras = new javax.swing.JButton();
        lblCampo = new javax.swing.JLabel();
        lblcorreo = new javax.swing.JLabel();
        lblCorreoV = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();

        jLabel20.setFont(new java.awt.Font("Tw Cen MT", 0, 12)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(255, 0, 0));
        jLabel20.setText("*");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 102, 51));

        jLabel1.setFont(new java.awt.Font("Script MT Bold", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Bienvenidos a nuestra Tienda Virtual");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addContainerGap())
        );

        jPanelFondo.setBackground(new java.awt.Color(0, 0, 0));
        jPanelFondo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(51, 51, 51));

        jLabel2.setFont(new java.awt.Font("Tw Cen MT", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("¡Empieza la Compra!");

        jLabel3.setFont(new java.awt.Font("Tw Cen MT", 1, 16)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Eres una persona:");

        btnPersonaNatural.setBackground(new java.awt.Color(51, 51, 51));
        btnPersonaNatural.setFont(new java.awt.Font("Tw Cen MT", 2, 16)); // NOI18N
        btnPersonaNatural.setForeground(new java.awt.Color(255, 255, 255));
        btnPersonaNatural.setText("Natural");
        btnPersonaNatural.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(153, 153, 255)));
        btnPersonaNatural.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPersonaNaturalActionPerformed(evt);
            }
        });

        btnPersonaJuridica.setBackground(new java.awt.Color(51, 51, 51));
        btnPersonaJuridica.setFont(new java.awt.Font("Tw Cen MT", 2, 16)); // NOI18N
        btnPersonaJuridica.setForeground(new java.awt.Color(255, 255, 255));
        btnPersonaJuridica.setText("Juridica");
        btnPersonaJuridica.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(153, 153, 255)));
        btnPersonaJuridica.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPersonaJuridicaActionPerformed(evt);
            }
        });

        jLabel14.setFont(new java.awt.Font("Tw Cen MT", 1, 16)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("Ver Pedidos:");

        BtnPedidos.setBackground(new java.awt.Color(51, 51, 51));
        BtnPedidos.setFont(new java.awt.Font("Tw Cen MT", 0, 16)); // NOI18N
        BtnPedidos.setForeground(new java.awt.Color(255, 255, 255));
        BtnPedidos.setText("Pedidos");
        BtnPedidos.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(153, 153, 255)));
        BtnPedidos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnPedidosActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 173, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(BtnPedidos, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(btnPersonaJuridica, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnPersonaNatural, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel3))
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addGap(6, 6, 6)
                                    .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 69, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnPersonaNatural, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnPersonaJuridica, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(89, 89, 89)
                .addComponent(jLabel14)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(BtnPedidos, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(61, 61, 61))
        );

        jPanelFondo.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 440));

        jLabel5.setFont(new java.awt.Font("Tw Cen MT", 0, 16)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("No Tengas miedo de renunciar a lo bueno");
        jPanelFondo.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 0, 300, 30));

        jLabel15.setFont(new java.awt.Font("Tw Cen MT", 0, 16)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel15.setText(" para ir a por lo mejor...");
        jPanelFondo.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 390, 297, 33));

        jPanelJunto.setBackground(new java.awt.Color(51, 51, 51));

        jPanelAmbos.setBackground(new java.awt.Color(102, 102, 102));

        jLabel10.setFont(new java.awt.Font("Tw Cen MT", 1, 12)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Direccion:");

        txtDireccionN.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtDireccionNKeyReleased(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Tw Cen MT", 1, 12)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Telefono:");

        txtTelefonoN.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtTelefonoNKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtTelefonoNKeyTyped(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Tw Cen MT", 1, 12)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Correo:");

        txtCorreoN.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtCorreoNKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtCorreoNKeyTyped(evt);
            }
        });

        lblDire.setFont(new java.awt.Font("Tw Cen MT", 0, 12)); // NOI18N
        lblDire.setForeground(new java.awt.Color(255, 0, 0));

        lblTel.setFont(new java.awt.Font("Tw Cen MT", 0, 12)); // NOI18N
        lblTel.setForeground(new java.awt.Color(255, 0, 0));

        lblCorreo.setFont(new java.awt.Font("Tw Cen MT", 0, 12)); // NOI18N
        lblCorreo.setForeground(new java.awt.Color(255, 0, 0));

        javax.swing.GroupLayout jPanelAmbosLayout = new javax.swing.GroupLayout(jPanelAmbos);
        jPanelAmbos.setLayout(jPanelAmbosLayout);
        jPanelAmbosLayout.setHorizontalGroup(
            jPanelAmbosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelAmbosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelAmbosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelAmbosLayout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblDire, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelAmbosLayout.createSequentialGroup()
                        .addComponent(jLabel11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblTel, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelAmbosLayout.createSequentialGroup()
                        .addComponent(jLabel12)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblCorreo, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(txtTelefonoN, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCorreoN, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtDireccionN, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        jPanelAmbosLayout.setVerticalGroup(
            jPanelAmbosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelAmbosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelAmbosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(lblDire))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtDireccionN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelAmbosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(lblTel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtTelefonoN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelAmbosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(lblCorreo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtCorreoN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14))
        );

        jPanelNatural.setBackground(new java.awt.Color(102, 102, 102));

        jLabel4.setFont(new java.awt.Font("Tw Cen MT", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Primer Nombre:");

        txtNombre1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtNombre1KeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtNombre1KeyTyped(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Tw Cen MT", 1, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Segundo Nombre:");

        txtNombre2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtNombre2KeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtNombre2KeyTyped(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Tw Cen MT", 1, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Primer Apellido:");

        txtApellido1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtApellido1KeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtApellido1KeyTyped(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Tw Cen MT", 1, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Segundo Apellido:");

        txtApellido2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtApellido2KeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtApellido2KeyTyped(evt);
            }
        });

        txtDocumento.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtDocumentoKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtDocumentoKeyTyped(evt);
            }
        });

        jLabel13.setFont(new java.awt.Font("Tw Cen MT", 1, 12)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Documento Id:");

        lblNom1.setFont(new java.awt.Font("Tw Cen MT", 0, 12)); // NOI18N
        lblNom1.setForeground(new java.awt.Color(255, 0, 0));

        lblNom2.setFont(new java.awt.Font("Tw Cen MT", 0, 12)); // NOI18N
        lblNom2.setForeground(new java.awt.Color(255, 0, 0));

        lblApell1.setFont(new java.awt.Font("Tw Cen MT", 0, 12)); // NOI18N
        lblApell1.setForeground(new java.awt.Color(255, 0, 0));

        lblApell2.setFont(new java.awt.Font("Tw Cen MT", 0, 12)); // NOI18N
        lblApell2.setForeground(new java.awt.Color(255, 0, 0));

        lblDocum.setFont(new java.awt.Font("Tw Cen MT", 0, 12)); // NOI18N
        lblDocum.setForeground(new java.awt.Color(255, 0, 0));

        javax.swing.GroupLayout jPanelNaturalLayout = new javax.swing.GroupLayout(jPanelNatural);
        jPanelNatural.setLayout(jPanelNaturalLayout);
        jPanelNaturalLayout.setHorizontalGroup(
            jPanelNaturalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelNaturalLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelNaturalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelNaturalLayout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblNom1, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(txtNombre1, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanelNaturalLayout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblNom2, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(txtNombre2, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanelNaturalLayout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblApell1, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(txtApellido1, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanelNaturalLayout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblApell2, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(txtApellido2, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtDocumento, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanelNaturalLayout.createSequentialGroup()
                        .addComponent(jLabel13)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblDocum, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(15, Short.MAX_VALUE))
        );
        jPanelNaturalLayout.setVerticalGroup(
            jPanelNaturalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelNaturalLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelNaturalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(lblNom1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtNombre1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelNaturalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(lblNom2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtNombre2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelNaturalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(lblApell1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtApellido1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelNaturalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(lblApell2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtApellido2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelNaturalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(lblDocum))
                .addGap(2, 2, 2)
                .addComponent(txtDocumento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(9, Short.MAX_VALUE))
        );

        jPanelJuridica.setBackground(new java.awt.Color(102, 102, 102));

        jLabel17.setFont(new java.awt.Font("Tw Cen MT", 1, 12)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setText("Razon Social:");

        txtRazonSocial.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtRazonSocialKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtRazonSocialKeyTyped(evt);
            }
        });

        jLabel18.setFont(new java.awt.Font("Tw Cen MT", 1, 12)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setText("NIT:");

        txtNit.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtNitKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtNitKeyTyped(evt);
            }
        });

        lblRazon.setFont(new java.awt.Font("Tw Cen MT", 0, 12)); // NOI18N
        lblRazon.setForeground(new java.awt.Color(255, 0, 0));

        lblNit.setFont(new java.awt.Font("Tw Cen MT", 0, 12)); // NOI18N
        lblNit.setForeground(new java.awt.Color(255, 0, 0));

        javax.swing.GroupLayout jPanelJuridicaLayout = new javax.swing.GroupLayout(jPanelJuridica);
        jPanelJuridica.setLayout(jPanelJuridicaLayout);
        jPanelJuridicaLayout.setHorizontalGroup(
            jPanelJuridicaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelJuridicaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelJuridicaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelJuridicaLayout.createSequentialGroup()
                        .addComponent(jLabel17)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblRazon, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(txtRazonSocial, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanelJuridicaLayout.createSequentialGroup()
                        .addComponent(jLabel18)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblNit, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(txtNit, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        jPanelJuridicaLayout.setVerticalGroup(
            jPanelJuridicaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelJuridicaLayout.createSequentialGroup()
                .addGroup(jPanelJuridicaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(lblRazon))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtRazonSocial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelJuridicaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18)
                    .addComponent(lblNit))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtNit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32))
        );

        btnCompras.setBackground(new java.awt.Color(51, 51, 51));
        btnCompras.setFont(new java.awt.Font("Tw Cen MT", 0, 18)); // NOI18N
        btnCompras.setForeground(new java.awt.Color(255, 255, 255));
        btnCompras.setText("Ir de Compras");
        btnCompras.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 255, 153)));
        btnCompras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnComprasActionPerformed(evt);
            }
        });

        lblCampo.setFont(new java.awt.Font("Tw Cen MT", 0, 12)); // NOI18N
        lblCampo.setForeground(new java.awt.Color(255, 0, 0));

        javax.swing.GroupLayout jPanelJuntoLayout = new javax.swing.GroupLayout(jPanelJunto);
        jPanelJunto.setLayout(jPanelJuntoLayout);
        jPanelJuntoLayout.setHorizontalGroup(
            jPanelJuntoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelJuntoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelJuntoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelJuntoLayout.createSequentialGroup()
                        .addGroup(jPanelJuntoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanelAmbos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanelJuridica, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanelNatural, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btnCompras, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(jPanelJuntoLayout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addComponent(lblCampo)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelJuntoLayout.setVerticalGroup(
            jPanelJuntoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelJuntoLayout.createSequentialGroup()
                .addComponent(lblCampo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelJuntoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelJuntoLayout.createSequentialGroup()
                        .addComponent(jPanelAmbos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanelJuridica, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanelJuntoLayout.createSequentialGroup()
                        .addComponent(jPanelNatural, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnCompras, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanelFondo.add(jPanelJunto, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 55, -1, 340));

        lblcorreo.setFont(new java.awt.Font("Tw Cen MT", 0, 12)); // NOI18N
        lblcorreo.setForeground(new java.awt.Color(255, 0, 0));
        jPanelFondo.add(lblcorreo, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 40, -1, -1));

        lblCorreoV.setFont(new java.awt.Font("Tw Cen MT", 0, 12)); // NOI18N
        lblCorreoV.setForeground(new java.awt.Color(255, 0, 0));
        jPanelFondo.add(lblCorreoV, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 40, -1, -1));

        jMenuBar1.setBackground(new java.awt.Color(255, 51, 0));

        jMenu1.setText("Administracion de productos");
        jMenu1.setFont(new java.awt.Font("Tw Cen MT", 0, 14)); // NOI18N

        jMenuItem1.setFont(new java.awt.Font("Tw Cen MT", 0, 12)); // NOI18N
        jMenuItem1.setText("Administrar Un producto");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanelFondo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanelFondo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnPersonaNaturalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPersonaNaturalActionPerformed
        jPanelJunto.setVisible(true);
        jPanelAmbos.setVisible(true);
        jPanelNatural.setVisible(true);
        jPanelJuridica.setVisible(false);
    }//GEN-LAST:event_btnPersonaNaturalActionPerformed

    private void btnPersonaJuridicaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPersonaJuridicaActionPerformed
        jPanelJunto.setVisible(true);
        jPanelAmbos.setVisible(true);
        jPanelJuridica.setVisible(true);
        jPanelNatural.setVisible(false);
    }//GEN-LAST:event_btnPersonaJuridicaActionPerformed

    private void btnComprasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnComprasActionPerformed
        
       ValidarEntrada();
          
    }//GEN-LAST:event_btnComprasActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        this.hide();
        FrmAdministrar fAdmin= new FrmAdministrar();
        fAdmin.setVisible(true);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void txtTelefonoNKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTelefonoNKeyTyped
        v.ValidarNumeros(evt); 
    }//GEN-LAST:event_txtTelefonoNKeyTyped

    private void txtNombre1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNombre1KeyTyped
        v.ValidarCaracteres(evt);
    }//GEN-LAST:event_txtNombre1KeyTyped

    private void txtNombre2KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNombre2KeyTyped
        v.ValidarCaracteres(evt);
    }//GEN-LAST:event_txtNombre2KeyTyped

    private void txtApellido1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtApellido1KeyTyped
        v.ValidarCaracteres(evt);
    }//GEN-LAST:event_txtApellido1KeyTyped

    private void txtApellido2KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtApellido2KeyTyped
        v.ValidarCaracteres(evt);
    }//GEN-LAST:event_txtApellido2KeyTyped

    private void txtDocumentoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtDocumentoKeyTyped
        v.ValidarNumeros(evt);
    }//GEN-LAST:event_txtDocumentoKeyTyped

    private void txtNitKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNitKeyTyped
        v.ValidarNumeros(evt);
    }//GEN-LAST:event_txtNitKeyTyped

    private void txtCorreoNKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCorreoNKeyTyped
        v.ValidarCorreo(evt); 
    }//GEN-LAST:event_txtCorreoNKeyTyped

    private void txtDireccionNKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtDireccionNKeyReleased
        ValidarCamposVacios();
        HabilitarBoton();
    }//GEN-LAST:event_txtDireccionNKeyReleased

    private void txtTelefonoNKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTelefonoNKeyReleased
        ValidarCamposVacios();
        HabilitarBoton();
    }//GEN-LAST:event_txtTelefonoNKeyReleased

    private void txtCorreoNKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCorreoNKeyReleased
        ValidarCamposVacios();
        HabilitarBoton();
    }//GEN-LAST:event_txtCorreoNKeyReleased

    private void txtRazonSocialKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtRazonSocialKeyReleased
        ValidarCamposVacios();
        HabilitarBoton();
    }//GEN-LAST:event_txtRazonSocialKeyReleased

    private void txtNitKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNitKeyReleased
        ValidarCamposVacios();
        HabilitarBoton();
    }//GEN-LAST:event_txtNitKeyReleased

    private void txtNombre1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNombre1KeyReleased
        ValidarCamposVacios();
        HabilitarBoton();
    }//GEN-LAST:event_txtNombre1KeyReleased

    private void txtNombre2KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNombre2KeyReleased
        HabilitarBoton();
    }//GEN-LAST:event_txtNombre2KeyReleased

    private void txtApellido1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtApellido1KeyReleased
        ValidarCamposVacios();
        HabilitarBoton();
    }//GEN-LAST:event_txtApellido1KeyReleased

    private void txtApellido2KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtApellido2KeyReleased
        HabilitarBoton();
    }//GEN-LAST:event_txtApellido2KeyReleased

    private void txtDocumentoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtDocumentoKeyReleased
        ValidarCamposVacios();
        HabilitarBoton();
    }//GEN-LAST:event_txtDocumentoKeyReleased

    private void txtRazonSocialKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtRazonSocialKeyTyped
        v.ValidarCaracteres(evt);
    }//GEN-LAST:event_txtRazonSocialKeyTyped

    private void BtnPedidosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnPedidosActionPerformed
        FrmPedidos p= new FrmPedidos();
        p.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_BtnPedidosActionPerformed
    //Confirma las validaciones de clientes para poder comprar productos
    public void ValidarEntrada()
    {
         if(this.jPanelJuridica.isVisible()==true)
        {
            if (this.ComparandoPersonaJ()==true) {
               this.InsertarPersonaJ();
               LimpiarTexto();
               FrmProductos abrirForm= new FrmProductos();
               abrirForm.setVisible(true);
               this.dispose();
            }else if(this.ComparandoPersonaJ()==false)
            {
                int salida=JOptionPane.showConfirmDialog(null,"Desea Continuar?", "Usted ya esta registrado en DB",JOptionPane.YES_NO_OPTION,JOptionPane.WARNING_MESSAGE);
                
                if (salida==0) {
                    
                    JOptionPane.showMessageDialog(null, "Logueo Exitoso");
                    LimpiarTexto();
                    FrmProductos abrirForm= new FrmProductos();
                    abrirForm.setVisible(true);
                    this.dispose();
                }else if(salida==1)
                {
                    LimpiarTexto();
                }
            }   
        }else if(this.jPanelNatural.isVisible()==true){
            
            if (this.ComparandoPersonaN()==true) {
                this.InsertarPersonaN();
                LimpiarTexto();
                FrmProductos abrirForm= new FrmProductos();
                abrirForm.setVisible(true);
                this.dispose();
            }else if(this.ComparandoPersonaN()==false)
            {
                int salida=JOptionPane.showConfirmDialog(null,"Desea Continuar?", "Usted ya se encuentra registrada en la base de datos",JOptionPane.YES_NO_OPTION,JOptionPane.WARNING_MESSAGE);
                
                if (salida==0) {
                    
                    JOptionPane.showMessageDialog(null, "Logueo Exitoso");
                    LimpiarTexto();
                    FrmProductos abrirForm= new FrmProductos();
                    abrirForm.setVisible(true);
                    this.dispose();
                    
                }else if(salida==1)
                {
                    LimpiarTexto();
                }
            }
            
        }
        
    }
    //Valida que cada casilla del formulario no este vacia o nula
    public boolean ValidarCamposVacios()
    {
        boolean flag=false;
        
        if(this.jPanelJuridica.isVisible()==true)
        {
            //Validar que el texto telefono no este vacio
            if(this.txtTelefonoN.getText().isEmpty())
            {
                this.lblTel.setText("*");
                this.lblCampo.setText("*Campos requeridos");
                flag=false;
            }else
            {
                this.lblTel.setText("");
                this.lblCampo.setText("");
                flag=true;
            }
            //Validar que correo no este vacio y que tenga los caracteres @ y .
            if(this.txtCorreoN.getText().isEmpty())
            {
                this.lblCorreo.setText("*");
                this.lblCampo.setText("*Campos requeridos");
                flag=false;
            }else if(!this.txtCorreoN.getText().contains("@")||!this.txtCorreoN.getText().contains("."))
            {
                this.lblCorreo.setText("*");
                this.lblCorreoV.setText("Correo no valido debe contener un @ y un .");
                flag=false;
            }else
            {
                this.lblCorreo.setText("");
                this.lblCampo.setText("");
                this.lblCorreoV.setText("");
                flag=true;
            }
            //Validar que la direccion no este vacia
            if(this.txtDireccionN.getText().isBlank())
            {
                this.lblDire.setText("*");
                this.lblCampo.setText("*Campos requeridos");
                flag=false;
            }else
            {
                this.lblDire.setText("");
                this.lblCampo.setText("");
                flag=true;
            }
            //Validar que la razon Social no esta vacio
            if (this.txtRazonSocial.getText().isBlank()) {
                this.lblRazon.setText("*");
                this.lblCampo.setText("*Campos requeridos");
                flag=false;
            }else
            {
                this.lblRazon.setText("");
                this.lblCampo.setText("");
                flag=true;
            }
            //Validar que el nit no este vacio
            if(this.txtNit.getText().isBlank())
            {
                this.lblCampo.setText("*Campos requeridos");
                this.lblNit.setText("*");
                flag=false;

            }else
            {
                this.lblNit.setText("");
                this.lblCampo.setText("");
                flag=true;
            }
            
            return flag;
        }else if(this.jPanelNatural.isVisible()==true)
        {
           //Validar que el texto telefono no este vacio
            if(this.txtTelefonoN.getText().isEmpty())
            {
                this.lblTel.setText("*");
                this.lblCampo.setText("*Campos requeridos");
                flag=false;
            }else
            {
                this.lblTel.setText("");
                this.lblCampo.setText("");
                flag=true;
            }
            //Validar que correo no este vacio y que tenga los caracteres @ y .
            if(this.txtCorreoN.getText().isEmpty())
            {
                this.lblCorreo.setText("*");
                this.lblCampo.setText("*Campos requeridos");
                flag=false;
            }else if(!this.txtCorreoN.getText().contains("@")||!this.txtCorreoN.getText().contains("."))
            {
                this.lblCorreo.setText("*");
                this.lblCorreoV.setText("Correo no valido debe contener un @ y un .");
                flag=false;
            }else
            {
                this.lblCorreo.setText("");
                this.lblCampo.setText("");
                this.lblCorreoV.setText("");
                flag=true;
            }
            //Validar que la direccion no este vacia
            if(this.txtDireccionN.getText().isBlank())
            {
                this.lblDire.setText("*");
                this.lblCampo.setText("*Campos requeridos");
                flag=false;
            }else
            {
                this.lblDire.setText("");
                this.lblCampo.setText("");
                flag=true;
            }
            //validar que el nombre1 no este vacio
            if(this.txtNombre1.getText().isBlank())
            {
                this.lblNom1.setText("*");
                this.lblCampo.setText("*Campos requeridos");
                flag=false;
            }else
            {
                this.lblNom1.setText("");
                this.lblCampo.setText("");
                flag=true;
            }
            //Validar que el apellido 1 no este vacio
            if(this.txtApellido1.getText().isEmpty())
            {
                this.lblApell1.setText("*");
                this.lblCampo.setText("*Campos requeridos");
                flag=false;
            }else
            {
                this.lblApell1.setText("");
                this.lblCampo.setText("");
                flag=true;
            }
            // validar que el documento noi este vacio
            if (this.txtDocumento.getText().isBlank()) {

               this.lblDocum.setText("*");
               this.lblCampo.setText("*Campo requerido");
               flag=false;
           }else
           {
               this.lblDocum.setText("");
               this.lblCampo.setText("");
               flag=true;
           }
            
            return flag;
        }
  
        return flag;
    }
    
    
    
    // Habilita unicamente el boton cuando las casillas enten completadas
    public void HabilitarBoton()
    {
        if(ValidarCamposVacios()==false || (!this.lblCorreo.getText().isEmpty()))
        {
            this.btnCompras.setEnabled(false);
        }else
        {
            this.btnCompras.setEnabled(true);
        }
           
    }
//Limpia las casillas de los textos
    public void LimpiarTexto()
    {
        this.txtDireccionN.setText("");
        this.txtTelefonoN.setText("");
        this.txtCorreoN.setText("");
        this.txtRazonSocial.setText("");
        this.txtNit.setText("");
        this.txtNombre1.setText("");
        this.txtNombre2.setText("");
        this.txtApellido1.setText("");
        this.txtApellido2.setText("");
        this.txtDocumento.setText("");
        
    }
    //Inserta una persona natural a la BD
    public void InsertarPersonaN()
    {
        Natural n= new Natural();
        Administrar admi=new Administrar();
        
        //setea los datos del objeto natural agarrando de las casillas de los textos
        n.setDireccion(this.txtDireccionN.getText());
        n.setTelefono(Integer.parseInt(this.txtTelefonoN.getText()));
        n.setCorreo(this.txtCorreoN.getText());
        n.setPrimerNombre(this.txtNombre1.getText());
        n.setSegundoNombre(this.txtNombre2.getText());
        n.setPrimerApellido(this.txtApellido1.getText());
        n.setSegundoApellido(this.txtApellido2.getText());
        n.setDocumentoId(Integer.parseInt(this.txtDocumento.getText()));
        
        //retorna el metodo 1 si se realizo la conexion e inserto el registro y diferente si no 
        int r= admi.InsertarClienteNatural(n);
        if (r==1) {
            JOptionPane.showMessageDialog(this,"Se agrego un cliente tipo Natural");
        }else
        {
            JOptionPane.showInputDialog(this,"Error al cargar el cliente tiipo Natural");
        }
    }
    //Inserta una persona juridica en la bd 
    public void InsertarPersonaJ()
    {
        Juridica j= new Juridica();
        Administrar admi=new Administrar();
        
        //setea los datos del objeto natural agarrando de las casillas de los textos
        j.setDireccion(this.txtDireccionN.getText());
        j.setTelefono(Integer.parseInt(this.txtTelefonoN.getText()));
        j.setCorreo(this.txtCorreoN.getText());
        j.setRazonSocial(this.txtRazonSocial.getText());
        j.setNit(Integer.parseInt(this.txtNit.getText()));
        
        //retorna el metodo 1 si se realizo la conexion e inserto el registro y diferente si no 
        int r= admi.InsertarClienteJuridico(j);
        if (r==1) {
            JOptionPane.showMessageDialog(this,"Se agrego un cliente tipo Juridico");
        }else
        {
            JOptionPane.showInputDialog(this,"Error al cargar el cliente tipo Juridico");
        }
    }
    // Compara las personas naturales por numero de documento y agarra el numero id para loguearse
    public boolean ComparandoPersonaN()
    {
        boolean flag=false;
        Natural n1= new Natural();
        Administrar admi=new Administrar();
        n1.setDocumentoId(Integer.parseInt(this.txtDocumento.getText()));
        
        List<Natural> lista= admi.ListarNaturales();
        for (int i = 0;  i<lista.size(); i++) 
        {
            if (lista.get(i).getDocumentoId()==n1.getDocumentoId())
            {
                flag=false;
                ListaId.add(String.valueOf(lista.get(i).getIdCliente()));
                return flag;
            }else{
                flag = true;
                
            }
        }
 
        return flag;
    }
    //Compara las personas juridicas por su numero nit y agarra el numero id para loguearse
    public boolean ComparandoPersonaJ()
    {
        boolean flag=false;
        Juridica j1= new Juridica();
        Administrar admi=new Administrar();
        j1.setNit(Integer.parseInt(this.txtNit.getText()));
        
        List<Juridica> lista= admi.ListarJuridicos();
        for (int i = 0;  i<lista.size(); i++) 
        {
            if (lista.get(i).getNit()==j1.getNit())
            {
                flag=false;
                ListaId.add(String.valueOf(lista.get(i).getIdCliente()));
                return flag;
            }else{
                flag = true;
                
            }
        }
 
        return flag;
    }
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmMenu().setVisible(true);
            }
        });
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnPedidos;
    public javax.swing.JButton btnCompras;
    public javax.swing.JButton btnPersonaJuridica;
    public javax.swing.JButton btnPersonaNatural;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanelAmbos;
    private javax.swing.JPanel jPanelFondo;
    private javax.swing.JPanel jPanelJunto;
    private javax.swing.JPanel jPanelJuridica;
    private javax.swing.JPanel jPanelNatural;
    private javax.swing.JLabel lblApell1;
    private javax.swing.JLabel lblApell2;
    private javax.swing.JLabel lblCampo;
    private javax.swing.JLabel lblCorreo;
    private javax.swing.JLabel lblCorreoV;
    private javax.swing.JLabel lblDire;
    private javax.swing.JLabel lblDocum;
    private javax.swing.JLabel lblNit;
    private javax.swing.JLabel lblNom1;
    private javax.swing.JLabel lblNom2;
    private javax.swing.JLabel lblRazon;
    private javax.swing.JLabel lblTel;
    private javax.swing.JLabel lblcorreo;
    private javax.swing.JTextField txtApellido1;
    private javax.swing.JTextField txtApellido2;
    private javax.swing.JTextField txtCorreoN;
    private javax.swing.JTextField txtDireccionN;
    private javax.swing.JTextField txtDocumento;
    private javax.swing.JTextField txtNit;
    private javax.swing.JTextField txtNombre1;
    private javax.swing.JTextField txtNombre2;
    private javax.swing.JTextField txtRazonSocial;
    private javax.swing.JTextField txtTelefonoN;
    // End of variables declaration//GEN-END:variables
}

