/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;

import java.time.*;
import java.util.*;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

import modelo.*;

/**
 *
 * @author miche
 */
public class FrmProductos extends javax.swing.JFrame implements Runnable{
    public static ArrayList<Pedido> listaPedidos= new ArrayList<>();
    ArrayList carrito=new ArrayList();
    public static DefaultTableModel modelo2;
    String hora,min,seg,time;
    Thread h1;
    int filaProductos=0;
    /**
     * Creates new form FrmProductos
     */
    public FrmProductos() {
        initComponents();
        CargarDatosTabla();
        AgarrarIdCliente();
        modelo2=new DefaultTableModel();
        modelo2.addColumn("Id");
        modelo2.addColumn("Denominacion");
        modelo2.addColumn("Cantidad");
        modelo2.addColumn("Precio Total");
        jTableCarrito.setModel(modelo2);
        h1=new Thread(this);
        lbFechaInicio.setText(Carrito_Compra.InicializarFechaInicio());
        lbFechaFinal.setText(Carrito_Compra.InicializarFechaFinal());
        h1.start();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTablaProductos = new javax.swing.JTable();
        SpinnerCant = new javax.swing.JSpinner();
        jLabel2 = new javax.swing.JLabel();
        btnAgregarProducto = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTableCarrito = new javax.swing.JTable();
        txtTotal = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        btnAgregarProducto1 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        lbFechaInicio = new javax.swing.JLabel();
        lbFechaFinal = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        lbCronometro = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        lbIdCliente = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(51, 51, 51));

        jPanel2.setBackground(new java.awt.Color(255, 102, 51));

        jLabel1.setFont(new java.awt.Font("Tw Cen MT", 3, 20)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Lista de productos");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTablaProductos.setBackground(new java.awt.Color(102, 102, 102));
        jTablaProductos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id", "Denominacion", "Proveedor", "Stock", "Precio"
            }
        ));
        jScrollPane1.setViewportView(jTablaProductos);
        if (jTablaProductos.getColumnModel().getColumnCount() > 0) {
            jTablaProductos.getColumnModel().getColumn(0).setPreferredWidth(10);
            jTablaProductos.getColumnModel().getColumn(3).setPreferredWidth(25);
        }

        jLabel2.setFont(new java.awt.Font("Tw Cen MT", 1, 16)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Total:");

        btnAgregarProducto.setBackground(new java.awt.Color(51, 51, 51));
        btnAgregarProducto.setFont(new java.awt.Font("Tw Cen MT", 0, 16)); // NOI18N
        btnAgregarProducto.setForeground(new java.awt.Color(255, 255, 255));
        btnAgregarProducto.setText("Agregar");
        btnAgregarProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarProductoActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tw Cen MT", 0, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Añade al carrito");

        jTableCarrito.setBackground(new java.awt.Color(102, 102, 102));
        jTableCarrito.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id", "Denominacion", "Cantidad", "Precio Total"
            }
        ));
        jScrollPane2.setViewportView(jTableCarrito);
        if (jTableCarrito.getColumnModel().getColumnCount() > 0) {
            jTableCarrito.getColumnModel().getColumn(0).setPreferredWidth(10);
            jTableCarrito.getColumnModel().getColumn(2).setPreferredWidth(20);
        }

        txtTotal.setEditable(false);
        txtTotal.setBackground(new java.awt.Color(102, 102, 102));

        jLabel4.setFont(new java.awt.Font("Tw Cen MT", 1, 16)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Cantidad");

        btnAgregarProducto1.setBackground(new java.awt.Color(51, 51, 51));
        btnAgregarProducto1.setFont(new java.awt.Font("Tw Cen MT", 0, 16)); // NOI18N
        btnAgregarProducto1.setForeground(new java.awt.Color(255, 255, 255));
        btnAgregarProducto1.setText("Hacer Pedido");
        btnAgregarProducto1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarProducto1ActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Tw Cen MT", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Tienes Hasta:");

        lbFechaInicio.setForeground(new java.awt.Color(204, 204, 204));
        lbFechaInicio.setText(".");

        lbFechaFinal.setForeground(new java.awt.Color(204, 204, 204));
        lbFechaFinal.setText(".");

        jLabel7.setFont(new java.awt.Font("Tw Cen MT", 0, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Fecha de realizacion:");

        lbCronometro.setForeground(new java.awt.Color(204, 204, 204));
        lbCronometro.setText("time");

        jLabel9.setFont(new java.awt.Font("Tw Cen MT", 0, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Cronometro:");

        jLabel6.setFont(new java.awt.Font("Tw Cen MT", 0, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("ID: Cliente");

        lbIdCliente.setFont(new java.awt.Font("Tw Cen MT", 0, 12)); // NOI18N
        lbIdCliente.setForeground(new java.awt.Color(204, 204, 204));
        lbIdCliente.setText("ID");

        jLabel8.setFont(new java.awt.Font("Tw Cen MT", 2, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 255, 153));
        jLabel8.setText("Carrito de Compras");

        jButton1.setBackground(new java.awt.Color(51, 51, 51));
        jButton1.setFont(new java.awt.Font("Tw Cen MT", 0, 16)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Quitar");
        jButton1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 51, 0)));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 322, Short.MAX_VALUE)
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(SpinnerCant, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel2)
                                    .addComponent(btnAgregarProducto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel3)
                                    .addComponent(txtTotal)
                                    .addComponent(btnAgregarProducto1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel4)
                                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel7)
                                    .addComponent(lbFechaInicio))
                                .addGap(40, 40, 40)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lbFechaFinal)
                                    .addComponent(jLabel5)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(lbIdCliente))
                            .addComponent(jLabel8))
                        .addContainerGap(22, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addGap(27, 27, 27)
                        .addComponent(lbCronometro)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(lbIdCliente))
                .addGap(7, 7, 7)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(10, 10, 10)
                        .addComponent(SpinnerCant, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnAgregarProducto))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbFechaFinal)
                    .addComponent(lbFechaInicio))
                .addGap(12, 12, 12)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbCronometro)
                    .addComponent(jLabel9))
                .addGap(18, 18, 18)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnAgregarProducto1))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(16, 16, 16))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAgregarProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarProductoActionPerformed
        
        int fila=this.jTablaProductos.getSelectedRow();
        if (fila==-1) {
            JOptionPane.showMessageDialog(this, "Debe seleccionar una fila.");
        }else{
            AgregarProductoCarrito();
           
        }
        
    }//GEN-LAST:event_btnAgregarProductoActionPerformed

    private void btnAgregarProducto1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarProducto1ActionPerformed
       
        
        if (this.jTableCarrito.getRowCount()==0) {
            int salida=JOptionPane.showConfirmDialog(null,"Desea Continuar?", "Usted no selecciono ningun producto",JOptionPane.YES_NO_OPTION,JOptionPane.WARNING_MESSAGE);
             if (salida==0) {
                JOptionPane.showMessageDialog(null,"Debe agregar productos al carrito ");
            }else
             {
                dispose();
                FrmMenu m= new FrmMenu();
                m.setVisible(true);
             }
   
        }else{
            InsertarPedido();
            String id=Administrar.ListaId.get(0);
            EditarCantidadProductosDB();
            JOptionPane.showMessageDialog(null,"Pedido Realizado con el id: "+id);
            Administrar.ListaId.clear();
            h1.stop();
            dispose();
            FrmMenu m= new FrmMenu();
            m.setVisible(true);
            
        }    
    }//GEN-LAST:event_btnAgregarProducto1ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        int fila= this.jTableCarrito.getSelectedRow();
        if (fila==-1) {
            JOptionPane.showMessageDialog(null,"Para quitar un producto debe seleccionar una fila del carrito");
        }else
        {
           QuitarProductoCarrito(); 
        }
        
    }//GEN-LAST:event_jButton1ActionPerformed
   //Quita ell producto seleccionado en la tabla del carrito y agrega su cantidad a la tabla de productos
    public void QuitarProductoCarrito()
    {
        int fila=this.jTableCarrito.getSelectedRow();
        int cant=Integer.parseInt(this.jTableCarrito.getValueAt(fila, 2).toString());
        int id=Integer.parseInt(this.jTableCarrito.getValueAt(fila, 0).toString());
        int cantP, suma;
        float precio=Float.parseFloat(this.jTableCarrito.getValueAt(fila, 3).toString());
        float aux, restaT;
        for (int i = 0; i <this.jTablaProductos.getRowCount(); i++) {
            
            if (id==Integer.parseInt(this.jTablaProductos.getValueAt(i, 0).toString()))
            {
                cantP=Integer.parseInt(this.jTablaProductos.getValueAt(i, 3).toString());
                suma=cantP+cant;
                aux=Float.parseFloat(this.txtTotal.getText());
                restaT=aux-precio;
                this.jTablaProductos.setValueAt(suma, i, 3);
                this.txtTotal.setText(String.valueOf(restaT));
                DefaultTableModel modelo=(DefaultTableModel)this.jTableCarrito.getModel();
                modelo.removeRow(fila);
            }
        }
    
    }
    //Crea un objeto pedido y administrar, setea el pedido con los productos de la tabla carrito y los agrega a la DB
    public void InsertarPedido(){
        Pedido p=new Pedido();
        Administrar admi= new Administrar();
        
        p.setIdCliente(Integer.parseInt(this.lbIdCliente.getText()));
        p.setFechaPedido(LocalDate.now());
        p.setTotal(Float.parseFloat(this.txtTotal.getText()));
        p.setEstado(Pedido.Estado.PENDIENTE);
        
        int r= admi.AgregarPedido(p);
        if (r==1) {
            JOptionPane.showMessageDialog(this,"Se agrego el pedido correctamente");
        }else
        {
            JOptionPane.showInputDialog(this,"Error al cargar el pedido");
        }
    }
    public void AgarrarIdCliente()
    { 
        //Si el usuario esta registrado en la DB entra
        if (Administrar.ListaId.isEmpty()) {
            //valida que no este null o vacio el id del usuario repetido
            if(FrmMenu.ListaId !=null && !FrmMenu.ListaId.isEmpty())
            {
              String id=FrmMenu.ListaId.get(0);
              FrmMenu.ListaId.clear();
              this.lbIdCliente.setText(id);  
            }else
            {
                dispose();
                FrmMenu m= new FrmMenu();
                m.setVisible(true);
            }
            
        }else
        {
          String id=Administrar.ListaId.get(0);
          Administrar.ListaId.clear();
          lbIdCliente.setText(id);  
        }
        
        
    }
    
   
    public void SumarTotal()
    {
        int contar = jTableCarrito.getRowCount();
        float suma=0;
        float total=0;
        int aux=Integer.parseInt(SpinnerCant.getValue().toString());
        for (int i = 0; i < contar; i++) {
            suma=suma+Float.valueOf(jTableCarrito.getValueAt(i,3).toString());  
        }
        txtTotal.setText(String.valueOf(suma));
        
    }
   
    public void CargarDatosTabla()
    {
        LineaProducto lp= new LineaProducto();
        lp.Listar(jTablaProductos);
        
    }
    public void EditarCantidadProductosDB()
    {
        int filaSeleccionada=-1;
        LineaProducto p= new LineaProducto();
        Administrar admi=new Administrar();
        
        filaSeleccionada=jTablaProductos.getSelectedRow();
        String id=(String.valueOf(jTablaProductos.getValueAt(filaSeleccionada, 0)));
        p.setId(Integer.parseInt(id));
        String deno=((String)this.jTablaProductos.getValueAt(filaSeleccionada, 1));
        p.setDenominacion(deno);
        String provee=((String)this.jTablaProductos.getValueAt(filaSeleccionada, 2));
        p.setProveedor(provee);
        String cant=(String.valueOf(this.jTablaProductos.getValueAt(filaSeleccionada, 3)));
        p.setCantidad(Integer.parseInt(cant));
        String price=(String.valueOf(this.jTablaProductos.getValueAt(filaSeleccionada, 4)));
        p.setPrecio(Float.parseFloat(price));
        
        int r= admi.Modificar(p);
         if (r==1) {
             System.out.println("\"Se actualizo correctamente la DB. ");
        }else
         {
             System.out.println("Error al actualizar la DB");
         }
    }
    public void AgregarProductoCarrito()
    {
        int aux,value,resta;
        float total=0;
        float auxSuma=0;
        int fila=this.jTablaProductos.getSelectedRow();
        aux=Integer.parseInt(SpinnerCant.getValue().toString());
        this.filaProductos=fila;
        value=Integer.parseInt(jTablaProductos.getValueAt(fila, 3).toString());
        resta=value-aux;
        if(aux>0)
        {   
            if(value>0 && aux<=value)
            {
                jTablaProductos.setValueAt(resta, fila, 3);
                String Datos[]=new String[4];
                Datos[0]=jTablaProductos.getValueAt(fila, 0).toString();
                Datos[1]=jTablaProductos.getValueAt(fila, 1).toString();
                Datos[2]=SpinnerCant.getValue().toString();               
                auxSuma=Float.valueOf(jTablaProductos.getValueAt(fila, 4).toString());
                total=auxSuma*aux;
                Datos[3]=Float.toString(total);
                modelo2.addRow(Datos);
                SumarTotal();               
                
            }else
            {
                JOptionPane.showMessageDialog(null,"Superaste el limite Stock");
            }
        }else{
            JOptionPane.showMessageDialog(null, "ERROR. Debe agregar una cantidad");
        }
        SpinnerCant.setValue(0);
        
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmMenu().setVisible(true);
            }
        });
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JSpinner SpinnerCant;
    private javax.swing.JButton btnAgregarProducto;
    private javax.swing.JButton btnAgregarProducto1;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTablaProductos;
    private javax.swing.JTable jTableCarrito;
    private javax.swing.JLabel lbCronometro;
    private javax.swing.JLabel lbFechaFinal;
    private javax.swing.JLabel lbFechaInicio;
    public javax.swing.JLabel lbIdCliente;
    public javax.swing.JTextField txtTotal;
    // End of variables declaration//GEN-END:variables

    @Override
    public void run() {
        Thread ct=Thread.currentThread();
        
        while(ct==h1)
        {   
            Actualizar();
            lbCronometro.setText(hora+":"+min+":"+seg+" ");
            try{
               Thread.sleep(1000); 
            }catch(InterruptedException e){}
        }
    }
    public void Actualizar()
    {
        Calendar calendario=new GregorianCalendar();
        Date horaActual= new Date();
        calendario.setTime(horaActual);
           
        hora=calendario.get(Calendar.HOUR_OF_DAY)>9?""+calendario.get(Calendar.HOUR_OF_DAY):"0"+calendario.get(Calendar.HOUR_OF_DAY);
        min=calendario.get(Calendar.MINUTE)>9?""+calendario.get(Calendar.MINUTE):"0"+calendario.get(Calendar.MINUTE);
        seg=calendario.get(Calendar.SECOND)>9?""+calendario.get(Calendar.SECOND):"0"+calendario.get(Calendar.SECOND);      
    }
}
